In [1]:
import pandas as pd
import os

DATA_PATH = "../data/raw"

files = os.listdir(DATA_PATH)

files

['01_fund_master.csv',
 '02_nav_history.csv',
 '03_aum_by_fund_house.csv',
 '04_monthly_sip_inflows.csv',
 '05_category_inflows.csv',
 '06_industry_folio_count.csv',
 '07_scheme_performance.csv',
 '08_investor_transactions.csv',
 '09_portfolio_holdings.csv',
 '10_benchmark_indices.csv',
 'Axis_Bluechip.csv',
 'hdfc_top100_live_nav.csv',
 'ICICI_Bluechip.csv',
 'Kotak_Bluechip.csv',
 'Nippon_LargeCap.csv',
 'SBI_Bluechip.csv']

In [2]:
datasets = {}

for file in files:
    
    if file.endswith(".csv"):
        
        path = os.path.join(DATA_PATH, file)

        df = pd.read_csv(path)

        datasets[file] = df

print("Datasets Loaded:", len(datasets))

Datasets Loaded: 16

In [3]:
for name, df in datasets.items():

    print("\n" + "="*80)
    print("Dataset:", name)

================================================================================
Dataset: 01_fund_master.csv

================================================================================
Dataset: 02_nav_history.csv

================================================================================
Dataset: 03_aum_by_fund_house.csv

================================================================================
Dataset: 04_monthly_sip_inflows.csv

================================================================================
Dataset: 05_category_inflows.csv

================================================================================
Dataset: 06_industry_folio_count.csv

================================================================================
Dataset: 07_scheme_performance.csv

================================================================================
Dataset: 08_investor_transactions.csv

================================================================================
Dataset: 09_portfolio_holdings.csv

================================================================================
Dataset: 10_benchmark_indices.csv

================================================================================
Dataset: Axis_Bluechip.csv

================================================================================
Dataset: hdfc_top100_live_nav.csv

================================================================================
Dataset: ICICI_Bluechip.csv

================================================================================
Dataset: Kotak_Bluechip.csv

================================================================================
Dataset: Nippon_LargeCap.csv

================================================================================
Dataset: SBI_Bluechip.csv

In [4]:
print("\n Shape:")
print(df.shape)

 Shape:
(3240, 2)

In [5]:
df.dtypes

date     object
nav     float64
dtype: object

In [6]:
df.head

<bound method NDFrame.head of             date       nav
0     05-06-2026  105.1070
1     04-06-2026  104.8095
2     03-06-2026  104.7496
3     02-06-2026  104.7663
4     01-06-2026  104.7025
...          ...       ...
3235  08-01-2013  103.1663
3236  07-01-2013  103.1408
3237  04-01-2013  103.0619
3238  03-01-2013  103.0306
3239  02-01-2013  103.0059

[3240 rows x 2 columns]>

In [7]:
df.columns.tolist()

['date', 'nav']

In [8]:
print("Missing Values")
print(df.isnull().sum())

Missing Values
date    0
nav     0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
datasets["01_fund_master.csv"].head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [11]:
datasets["01_fund_master.csv"].columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='object')

In [12]:
fund_master = datasets["01_fund_master.csv"]

fund_master["fund_house"].nunique()

10

In [13]:
sorted(fund_master["fund_house"].unique())

['Aditya Birla Sun Life MF',
 'Axis Mutual Fund',
 'DSP Mutual Fund',
 'HDFC Mutual Fund',
 'ICICI Prudential MF',
 'Kotak Mahindra MF',
 'Mirae Asset MF',
 'Nippon India MF',
 'SBI Mutual Fund',
 'UTI Mutual Fund']

In [14]:
fund_master["category"].value_counts()

category
Equity    34
Debt       6
Name: count, dtype: int64

In [15]:
fund_master["sub_category"].value_counts()

sub_category
Large Cap          14
Mid Cap             7
Small Cap           6
Liquid              3
Gilt                2
Flexi Cap           2
Value               1
Short Duration      1
Index/ETF           1
Index               1
Large & Mid Cap     1
ELSS                1
Name: count, dtype: int64

In [16]:
fund_master["risk_category"].value_counts()

risk_category
Moderate           16
High                8
Very High           6
Low                 6
Moderately High     4
Name: count, dtype: int64

In [17]:
fund_master["amfi_code"].nunique()

40

In [18]:
len(fund_master)

40

In [19]:
# inspecting nav_history_dataset
nav_history = datasets["02_nav_history.csv"]

nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [20]:
nav_history.columns

Index(['amfi_code', 'date', 'nav'], dtype='object')

In [21]:
master_codes = set(
    fund_master["amfi_code"]
)

nav_codes = set(
    nav_history["amfi_code"]
)

missing_codes = master_codes - nav_codes

print("Missing Codes:", len(missing_codes))

Missing Codes: 0

In [22]:
# NOTE: 1. All AMFI codes in fund_master are present in nav_history.
#       2. Referential integrity is maintained.

In [23]:
matched = len(master_codes.intersection(nav_codes))

total = len(master_codes)

print(
    "Match Percentage:",
    round((matched/total)*100,2),
    "%"
)

Match Percentage: 100.0 %

In [24]:
nav_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [25]:
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [26]:
nav_history.duplicated().sum()

np.int64(0)

In [27]:
nav_history["date"] = pd.to_datetime(
    nav_history["date"])
print(
    nav_history["date"].min())
print(
    nav_history["date"].max())

2022-01-03 00:00:00
2026-05-29 00:00:00

In [28]:
# NOTE: NAV history spans from 2022 to 2026,providing adequate historical data or trend analysis

In [29]:
## . Fetch Live NAV from MFAPI

In [30]:
import requests
import pandas as pd

In [31]:
scheme_code = 125497

url = f"https://api.mfapi.in/mf/{scheme_code}"

response = requests.get(url)

print("Status Code:", response.status_code)

Status Code: 200

In [32]:
data = response.json()

data.keys()

dict_keys(['meta', 'data', 'status'])

In [33]:
data["meta"]

{'fund_house': 'SBI Mutual Fund',
 'scheme_type': 'Open Ended Schemes',
 'scheme_category': 'Equity Scheme - Small Cap Fund',
 'scheme_code': 125497,
 'scheme_name': 'SBI Small Cap Fund - Direct Plan - Growth',
 'isin_growth': 'INF200K01T51',
 'isin_div_reinvestment': None}

In [34]:
nav_df = pd.DataFrame(data["data"])

nav_df.head()

         date        nav
0  08-06-2026  191.90920
1  05-06-2026  194.75470
2  04-06-2026  194.52200
3  03-06-2026  194.08100
4  02-06-2026  193.12950

In [35]:
nav_df.columns

Index(['date', 'nav'], dtype='object')

In [36]:
nav_df.to_csv("../data/raw/hdfc_top100_live_nav.csv",index=False)

print("CSV Saved Successfully")

CSV Saved Successfully

In [37]:
import os

os.path.exists("../data/raw/hdfc_top100_live_nav.csv")

True

In [38]:
# Successfully connected to MFAPI and fetched NAV data for HDFC Top 100 Direct Fund (AMFI Code: 125497). 
# The API returned a valid JSON response with status code 200. 
# Historical NAV data was parsed into a Pandas DataFrame and saved as a raw CSV file for further analysis.

In [39]:
schemes = {
    "SBI_Bluechip":119551,
    "ICICI_Bluechip":120503,
    "Nippon_LargeCap":118632,
    "Axis_Bluechip":119092,
    "Kotak_Bluechip":120841
}

In [40]:
for name, code in schemes.items():

    url = f"https://api.mfapi.in/mf/{code}"
    response = requests.get(url)
    data = response.json()
    nav_df = pd.DataFrame(data["data"])
    nav_df.to_csv(f"../data/raw/{name}.csv",index=False)

    print(f"{name} downloaded successfully")

SBI_Bluechip downloaded successfully
ICICI_Bluechip downloaded successfully
Nippon_LargeCap downloaded successfully
Axis_Bluechip downloaded successfully
Kotak_Bluechip downloaded successfully

In [41]:
import os

csv_files = [f for f in os.listdir("../data/raw") if f.endswith(".csv")]

print("Total CSV Files:", len(csv_files))
print(csv_files)

Total CSV Files: 16
['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', 'Axis_Bluechip.csv', 'hdfc_top100_live_nav.csv', 'ICICI_Bluechip.csv', 'Kotak_Bluechip.csv', 'Nippon_LargeCap.csv', 'SBI_Bluechip.csv']